# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith

name: Spell checking
on:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0
      - name: spelling
        uses: briandfoy/check-spelling@0.0.17-bdf
        with:
          debug: 1
